// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Railway_Group01.Data;

#nullable disable

namespace Railway_Group01.Migrations
{
    [DbContext(typeof(RailwayDbContext))]
    partial class RailwayDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("Railway_Group01.Data.Booking", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Bookings");
                });

            modelBuilder.Entity("Railway_Group01.Data.BookingDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int>("SeatId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.HasIndex("SeatId")
                        .IsUnique();

                    b.ToTable("BookingDetailss");
                });

            modelBuilder.Entity("Railway_Group01.Data.Cancelling", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PNRNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Receiver")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RefundRuleId")
                        .HasColumnType("int");

                    b.Property<string>("Sender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("PNRNo")
                        .IsUnique();

                    b.HasIndex("RefundRuleId");

                    b.HasIndex("UserId");

                    b.ToTable("Cancellings");
                });

            modelBuilder.Entity("Railway_Group01.Data.Coach", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClassCode")
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("CoachNo")
                        .HasColumnType("int");

                    b.Property<int>("NoOfCompartments")
                        .HasColumnType("int");

                    b.Property<int>("NoOfSeats")
                        .HasColumnType("int");

                    b.Property<string>("TrainCode")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode");

                    b.HasIndex("TrainCode");

                    b.ToTable("Coach");
                });

            modelBuilder.Entity("Railway_Group01.Data.CoachClass", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.ToTable("CoachClasses");

                    b.HasData(
                        new
                        {
                            Code = "AC1",
                            Name = "AC First Class"
                        },
                        new
                        {
                            Code = "AC2",
                            Name = "AC Second Class"
                        },
                        new
                        {
                            Code = "AC3",
                            Name = "AC Third Class"
                        },
                        new
                        {
                            Code = "SL",
                            Name = "Sleeper Class"
                        },
                        new
                        {
                            Code = "GE",
                            Name = "General Class"
                        });
                });

            modelBuilder.Entity("Railway_Group01.Data.Fare", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClassCode")
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("TypeCode")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("ClassCode");

                    b.HasIndex("RouteId");

                    b.ToTable("Fare");
                });

            modelBuilder.Entity("Railway_Group01.Data.Feedback", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Comments")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<string>("Suggestions")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Railway_Group01.Data.Passenger", b =>
                {
                    b.Property<string>("ID")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("Birthday")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("PassengerTypeCode")
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("PassengerTypeCode");

                    b.HasIndex("UserId");

                    b.ToTable("Passengers");
                });

            modelBuilder.Entity("Railway_Group01.Data.PassengerType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("Discount")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Code");

                    b.ToTable("PassengerTypes");

                    b.ToTable("Refund");
                });

            modelBuilder.Entity("Railway_Group01.Data.RefundRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("RefundAmount")
                        .HasColumnType("int");

                    b.Property<decimal>("RefundFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ValidFrom")
                        .HasColumnType("int");

                    b.Property<int>("ValidTo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("RefundRule");
                });

            modelBuilder.Entity("Railway_Group01.Data.Route", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("EndStationId")
                        .HasColumnType("int");

                    b.Property<int>("StartStationId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EndStationId");

                    b.HasIndex("StartStationId");

                    b.ToTable("Route");
                });

            modelBuilder.Entity("Railway_Group01.Data.RouteDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("ArrivalStationId")
                        .HasColumnType("int");

                    b.Property<int>("DelayTime")
                        .HasColumnType("int");

                    b.Property<int>("DepartureStationId")
                        .HasColumnType("int");

                    b.Property<int>("Distance")
                        .HasColumnType("int");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<int>("TravelTime")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalStationId");

                    b.HasIndex("DepartureStationId");

                    b.HasIndex("RouteId");

                    b.ToTable("RouteDetails");
                });

            modelBuilder.Entity("Railway_Group01.Data.Schedule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime?>("Arrival")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("Departure")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("RouteId")
                        .HasColumnType("int");

                    b.Property<string>("TrainCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("TrainCode");

                    b.ToTable("Schedule");
                });

            modelBuilder.Entity("Railway_Group01.Data.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("NameOfDivision")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ZipCode")
                        .HasColumnType("int");

                    b.Property<int>("Zone")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Station");
                });

            modelBuilder.Entity("Railway_Group01.Data.Ticket", b =>
                {
                    b.Property<string>("PNRNo")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("BookingDetailId")
                        .HasColumnType("int");

                    b.Property<int?>("FareId")
                        .HasColumnType("int");

                    b.Property<string>("PassengerID")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("int");

                    b.HasKey("PNRNo");

                    b.HasIndex("BookingDetailId")
                        .IsUnique();

                    b.HasIndex("FareId");

                    b.HasIndex("PassengerID")
                        .IsUnique();

                    b.HasIndex("ScheduleId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Railway_Group01.Data.Train", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool>("IsRunning")
                        .HasColumnType("bit");

                    b.Property<string>("TypeCode")
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("Code");

                    b.HasIndex("TypeCode");

                    b.ToTable("Trains");

                    b.HasData(
                        new
                        {
                            Code = "SE1",
                            IsRunning = false,
                            TypeCode = "F"
                        },
                        new
                        {
                            Code = "SE2",
                            IsRunning = false,
                            TypeCode = "F"
                        },
                        new
                        {
                            Code = "SE3",
                            IsRunning = false,
                            TypeCode = "SF"
                        },
                        new
                        {
                            Code = "SE4",
                            IsRunning = false,
                            TypeCode = "SF"
                        },
                        new
                        {
                            Code = "SE5",
                            IsRunning = false,
                            TypeCode = "S"
                        },
                        new
                        {
                            Code = "SE6",
                            IsRunning = false,
                            TypeCode = "S"
                        });
                });

            modelBuilder.Entity("Railway_Group01.Data.TrainType", b =>
                {
                    b.Property<string>("Code")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Code");

                    b.ToTable("TrainTypes");

                    b.ToTable("Train");
                });

            modelBuilder.Entity("Railway_Group01.Data.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BookingId")
                        .HasColumnType("int");

                    b.Property<int?>("CancellingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Receiver")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Sender")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("BookingId");

                    b.ToTable("Transaction");
                });

            modelBuilder.Entity("Railway_Group01.Data.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Railway_Group01.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Railway_Group01.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railway_Group01.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Railway_Group01.Data.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Railway_Group01.Data.Booking", b =>
                {
                    b.HasOne("Railway_Group01.Data.User", "User")
                        .WithMany("Bookings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Railway_Group01.Data.BookingDetail", b =>
                {
                    b.HasOne("Railway_Group01.Data.Booking", "Booking")
                        .WithMany("BookingDetails")
                        .HasForeignKey("BookingId");

                    b.HasOne("Railway_Group01.Data.Seat", "Seat")
                        .WithOne("BookingDetail")
                        .HasForeignKey("Railway_Group01.Data.BookingDetail", "SeatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Booking");

                    b.Navigation("Seat");
                });

            modelBuilder.Entity("Railway_Group01.Data.Cancelling", b =>
                {
                    b.HasOne("Railway_Group01.Data.Ticket", "Ticket")
                        .WithOne("Cancelling")
                        .HasForeignKey("Railway_Group01.Data.Cancelling", "PNRNo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railway_Group01.Data.RefundRule", "RefundRule")
                        .WithMany()
                        .HasForeignKey("RefundRuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railway_Group01.Data.User", "User")
                        .WithMany("Cancellings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RefundRule");

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Railway_Group01.Data.Coach", b =>
                {
                    b.HasOne("Railway_Group01.Data.CoachClass", "Class")
                        .WithMany("Coaches")
                        .HasForeignKey("ClassCode");

                    b.HasOne("Railway_Group01.Data.Train", "Train")
                        .WithMany("Coaches")
                        .HasForeignKey("TrainCode");

                    b.Navigation("Class");

                    b.Navigation("Train");
                });

            modelBuilder.Entity("Railway_Group01.Data.Fare", b =>
                {
                    b.HasOne("Railway_Group01.Data.CoachClass", "Class")
                        .WithMany("Fares")
                        .HasForeignKey("ClassCode");

                    b.HasOne("Railway_Group01.Data.Route", "Route")
                        .WithMany("Fares")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railway_Group01.Data.TrainType", "TrainType")
                        .WithMany("Fares")
                        .HasForeignKey("TypeCode");

                    b.Navigation("Class");

                    b.Navigation("Route");

                    b.Navigation("TrainType");
                });

            modelBuilder.Entity("Railway_Group01.Data.Feedback", b =>
                {
                    b.HasOne("Railway_Group01.Data.User", "User")
                        .WithMany("Feedbacks")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Railway_Group01.Data.Passenger", b =>
                {
                    b.HasOne("Railway_Group01.Data.PassengerType", null)
                        .WithMany("Passengers")
                        .HasForeignKey("PassengerTypeCode");

                    b.HasOne("Railway_Group01.Data.User", "User")
                        .WithMany("Passengers")
                        .HasForeignKey("UserId");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Railway_Group01.Data.Route", b =>
                {
                    b.HasOne("Railway_Group01.Data.Station", "EndStation")
                        .WithMany("EndRoutes")
                        .HasForeignKey("EndStationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Railway_Group01.Data.Station", "StartStation")
                        .WithMany("StartRoutes")
                        .HasForeignKey("StartStationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EndStation");

                    b.Navigation("StartStation");
                });

            modelBuilder.Entity("Railway_Group01.Data.RouteDetail", b =>
                {
                    b.HasOne("Railway_Group01.Data.Station", "ArrivalStation")
                        .WithMany("ArrivalRouteDetails")
                        .HasForeignKey("ArrivalStationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Railway_Group01.Data.Station", "DepartureStation")
                        .WithMany("DepartureRouteDetails")
                        .HasForeignKey("DepartureStationId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Railway_Group01.Data.Route", "Route")
                        .WithMany("RouteDetails")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ArrivalStation");

                    b.Navigation("DepartureStation");

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Railway_Group01.Data.Schedule", b =>
                {
                    b.HasOne("Railway_Group01.Data.Route", "Route")
                        .WithMany("Schedules")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railway_Group01.Data.Train", "Train")
                        .WithMany("Schedules")
                        .HasForeignKey("TrainCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");
                });

            modelBuilder.Entity("Railway_Group01.Data.Ticket", b =>
                {
                    b.HasOne("Railway_Group01.Data.BookingDetail", "BookingDetail")
                        .WithOne("Ticket")
                        .HasForeignKey("Railway_Group01.Data.Ticket", "BookingDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railway_Group01.Data.Fare", "Fare")
                        .WithMany("Tickets")
                        .HasForeignKey("FareId");

                    b.HasOne("Railway_Group01.Data.Passenger", "Passenger")
                        .WithOne("Ticket")
                        .HasForeignKey("Railway_Group01.Data.Ticket", "PassengerID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Railway_Group01.Data.Schedule", "Schedule")
                        .WithMany("Tickets")
                        .HasForeignKey("ScheduleId");

                    b.Navigation("BookingDetail");

                    b.Navigation("Fare");

                    b.Navigation("Passenger");

                    b.Navigation("Schedule");
                });

            modelBuilder.Entity("Railway_Group01.Data.Train", b =>
                {
                    b.HasOne("Railway_Group01.Data.TrainType", "Type")
                        .WithMany("Trains")
                        .HasForeignKey("TypeCode");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("Railway_Group01.Data.Transaction", b =>
                {
                    b.HasOne("Railway_Group01.Data.Booking", "Booking")
                        .WithMany("Transactions")
                        .HasForeignKey("BookingId");

                    b.HasOne("Railway_Group01.Data.Cancelling", "Cancelling")
                        .WithMany("Transactions")
                        .HasForeignKey("CancellingId");

                    b.Navigation("Booking");

                    b.Navigation("Cancelling");
                });

            modelBuilder.Entity("Railway_Group01.Data.Booking", b =>
                {
                    b.Navigation("BookingDetails");

                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Railway_Group01.Data.BookingDetail", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Railway_Group01.Data.Cancelling", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Railway_Group01.Data.Coach", b =>
                {
                    b.Navigation("Seats");
                });

            modelBuilder.Entity("Railway_Group01.Data.CoachClass", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Fares");
                });

            modelBuilder.Entity("Railway_Group01.Data.Fare", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Railway_Group01.Data.Passenger", b =>
                {
                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Railway_Group01.Data.PassengerType", b =>
                {
                    b.Navigation("Passengers");
                });

            modelBuilder.Entity("Railway_Group01.Data.Route", b =>
                {
                    b.Navigation("Fares");

                    b.Navigation("RouteDetails");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Railway_Group01.Data.Schedule", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Railway_Group01.Data.Seat", b =>
                {
                    b.Navigation("BookingDetail");
                });

            modelBuilder.Entity("Railway_Group01.Data.Station", b =>
                {
                    b.Navigation("ArrivalRouteDetails");

                    b.Navigation("DepartureRouteDetails");

                    b.Navigation("EndRoutes");

                    b.Navigation("StartRoutes");
                });

            modelBuilder.Entity("Railway_Group01.Data.Ticket", b =>
                {
                    b.Navigation("Cancelling");
                });

            modelBuilder.Entity("Railway_Group01.Data.Train", b =>
                {
                    b.Navigation("Coaches");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("Railway_Group01.Data.TrainType", b =>
                {
                    b.Navigation("Fares");

                    b.Navigation("Trains");
                });

            modelBuilder.Entity("Railway_Group01.Data.User", b =>
                {
                    b.Navigation("Bookings");

                    b.Navigation("Cancellings");

                    b.Navigation("Feedbacks");

                    b.Navigation("Passengers");
                });
#pragma warning restore 612, 618
        }
    }
}
